// NOTE: this file is auto-generated by site-index.mjs
import fanbox from './fanbox.yml';
import plurk from './plurk.yml';
import twitter from './twitter.yml';

export default {
  [fanbox.id]: fanbox,
  [plurk.id]: plurk,
  [twitter.id]: twitter,
};

