import fs from 'fs/promises';

const names = [];

for await (const dirEntry of await fs.opendir('./src/sites')) {
  // filter yml files
  if (dirEntry.isFile() && dirEntry.name.endsWith('.yml')) {
    const name = dirEntry.name.slice(0, -4);
    names.push(name);
  }
}

// generate import statements
const imports = names.map(name => `import ${name} from './${name}.yml';`).join('\n');
// generate export object
const exports = `export default {\n${names.map(name => `  [${name}.id]: ${name},`).join('\n')}\n};\n`;

const content = `// NOTE: this file is auto-generated by site-index.mjs\n${imports}\n\n${exports}\n`;

await fs.writeFile('./src/sites/index.mjs', content);
